mport random

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

print("Welcome to the PyPassword Generator!")
nr_letters = int(input("How many letters would you like in your password?\n"))
nr_symbols = int(input(f"How many symbols would you like?\n"))
nr_numbers = int(input(f"How many numbers would you like?\n"))

password_gen = "" #Variable created to hold the output of each loop.

for number in range(0, nr_letters): #Sets up the loop count. 0 - X(input of user) amount of times
    letters_range = random.randint(0, 51) #Sets up the random number based on the count of data values in the list of potential characters (letters) that will be used to pull a value from range.
    ran_letter = letters[letters_range] #Randomly pulls a value from the variable "letters" based on the # generated by previous line.
    password_gen += ran_letter #Concatinates pulled value to this variable before restarting loop.

for number in range(0, nr_symbols): #Sets up the loop count. 0 - X(input of user) amount of times
    symbols_range = random.randint(0, 8) #Sets up the random number based on the count of data values in the list of potential characters (symbols) that will be used to pull a value from range.
    ran_symbol = symbols[symbols_range] #Randomly pulls a value from the variable "symbols" based on the # generated by previous line.
    password_gen += ran_symbol #Concatinates pulled value to this variable before restarting loop.

for number in range(0, nr_numbers): #Sets up the loop count. 0 - X(input of user) amount of times
    numbers_range = random.randint(0, 9) #Sets up the random number based on the count of data values in the list of potential characters (numbers) that will be used to pull a value from range.
    ran_number = numbers[numbers_range] #Randomly pulls a value from the variable "numbers" based on the # generated by previous line.
    password_gen += ran_number #Concatinates pulled value to this variable before restarting loop.
print(password_gen) #prints the final value of the password_gen variable based on the concatenation of all the outputs of the for loops sequentially.




