import random

letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

print("Welcome to the PyPassword Generator!")
nr_letters = int(input("How many letters would you like in your password?\n"))
nr_symbols = int(input(f"How many symbols would you like?\n"))
nr_numbers = int(input(f"How many numbers would you like?\n"))

password_gen = [] #Variable created to hold the output of each loop in a list.

for number in range(0, nr_letters): #Sets up the loop count. 0 - X(input of user) amount of times
    letters_range = random.randint(0, 51) #Sets up the random number based on the count of data values in the list of potential characters (letters) that will be used to pull a value from range.
    ran_letter = letters[letters_range] #Randomly pulls a value from the variable "letters" based on the # generated by previous line.
    password_gen.append(ran_letter) #Appends pulled value to this variable, creating a list before restarting loop.

for number in range(0, nr_symbols): #Sets up the loop count. 0 - X(input of user) amount of times
    symbols_range = random.randint(0, 8) #Sets up the random number based on the count of data values in the list of potential characters (symbols) that will be used to pull a value from range.
    ran_symbol = symbols[symbols_range] #Randomly pulls a value from the variable "symbols" based on the # generated by previous line.
    password_gen.append(ran_symbol) #Appends pulled value to this variable, creating a list before restarting loop.

for number in range(0, nr_numbers): #Sets up the loop count. 0 - X(input of user) amount of times
    numbers_range = random.randint(0, 9) #Sets up the random number based on the count of data values in the list of potential characters (numbers) that will be used to pull a value from range.
    ran_number = numbers[numbers_range]#Randomly pulls a value from the variable "numbers" based on the # generated by previous line.
    password_gen.append(ran_number) #Appends pulled value to this variable, creating a list before restarting loop.

sum_of_pass = nr_letters + nr_numbers + nr_symbols #Sum of the total number of inputs. Will be used to create the desired passwork length.
password_draft = random.sample(password_gen,sum_of_pass) #Randomly pulls the values from the password_gen table until the total sum of letters is reach. The pulled value is "Unique" meaning once a value is pulled it won't be used again.
password_final = ''.join(password_draft) #Converts the pulled values from a table to string, thus resulting in the final password.  

print(password_final)
